#!/usr/bin/env bash
# safety-guard.sh — Generated by agtop init
# Claude Code PreToolUse hook that blocks dangerous commands.
# Exit code 2 = block tool execution. Exit code 0 = allow.
# See: https://docs.anthropic.com/en/docs/claude-code/hooks

set -euo pipefail

# Read the tool input JSON from stdin
INPUT=$(cat)

# Extract the command field (jq with grep/sed fallback)
if command -v jq &>/dev/null; then
  COMMAND=$(echo "$INPUT" | jq -r '.tool_input.command // empty' 2>/dev/null)
else
  COMMAND=$(echo "$INPUT" | grep -o '"command"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"command"[[:space:]]*:[[:space:]]*"\(.*\)"/\1/' 2>/dev/null || true)
fi

if [ -z "$COMMAND" ]; then
  exit 0  # No command field — not a Bash tool call, allow
fi

# Blocked patterns (from agtop.toml safety.blocked_patterns)
if [[ "$COMMAND" =~ rm\s+-[rf]+\s+/ ]]; then
  echo "BLOCKED by agtop safety: pattern 'rm\s+-[rf]+\s+/' matched" >&2
  exit 2
fi
if [[ "$COMMAND" =~ git\s+push.*--force ]]; then
  echo "BLOCKED by agtop safety: pattern 'git\s+push.*--force' matched" >&2
  exit 2
fi
if [[ "$COMMAND" =~ DROP\s+TABLE ]]; then
  echo "BLOCKED by agtop safety: pattern 'DROP\s+TABLE' matched" >&2
  exit 2
fi
if [[ "$COMMAND" =~ (curl|wget).*\|\s*(sh|bash) ]]; then
  echo "BLOCKED by agtop safety: pattern '(curl|wget).*\|\s*(sh|bash)' matched" >&2
  exit 2
fi
if [[ "$COMMAND" =~ chmod\s+777 ]]; then
  echo "BLOCKED by agtop safety: pattern 'chmod\s+777' matched" >&2
  exit 2
fi

exit 0
